config/routes.rb
DigitalDiscretion::Application.routes.draw do
  resources :portfolios

  get "pages/home"

  get "pages/services"

  get "pages/contact"

  get "pages/about"

end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
  attr_accessible :description, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
   def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end

  def about
    @title = "About"
  end

  def services
  	@title = "Services"
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  # GET /portfolios
  # GET /portfolios.json
  def index
    @portfolios = Portfolio.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @portfolios }
    end
  end

  # GET /portfolios/1
  # GET /portfolios/1.json
  def show
    @portfolio = Portfolio.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @portfolio }
    end
  end

  # GET /portfolios/new
  # GET /portfolios/new.json
  def new
    @portfolio = Portfolio.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @portfolio }
    end
  end

  # GET /portfolios/1/edit
  def edit
    @portfolio = Portfolio.find(params[:id])
  end

  # POST /portfolios
  # POST /portfolios.json
  def create
    @portfolio = Portfolio.new(params[:portfolio])

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully created.' }
        format.json { render json: @portfolio, status: :created, location: @portfolio }
      else
        format.html { render action: "new" }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /portfolios/1
  # PUT /portfolios/1.json
  def update
    @portfolio = Portfolio.find(params[:id])

    respond_to do |format|
      if @portfolio.update_attributes(params[:portfolio])
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolios/1
  # DELETE /portfolios/1.json
  def destroy
    @portfolio = Portfolio.find(params[:id])
    @portfolio.destroy

    respond_to do |format|
      format.html { redirect_to portfolios_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Digital Discretion | <%= @title %></title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">Some Store</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Browse Products", portfolios_path %></li>
            <li><%= link_to "Price List" %></li>
            <li><%= link_to "Contact Us" %></li>
            <li><%= link_to "Cart" %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
<div class="container">
	<div class="row">
		<div class="span9"><%= yield %></div>
		<div class="span3">
			<h2>About Us</h2>
			<p>Sed quis eros lorem. Morbi at orci non velit pulvinar accumsan at vel libero. Aenean posuere pulvinar erat et porta. Integer porta blandit nisi id vehicula. Sed adipiscing gravida purus, eget rhoncus dui elementum a. Duis nec mi ultricies neque pharetra imperdiet auctor at turpis. In ac ultrices ante.</p>

<p>Pellentesque eu diam vel enim rutrum dictum a quis nisl. Ut vitae nisl justo. In at elit ac metus sollicitudin congue sit amet a erat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed nec pellentesque lacus. Maecenas bibendum porttitor tempus. Vestibulum ut diam nec nibh bibendum sodales ac sed dui. Curabitur facilisis, nisi vel dictum vulputate, lorem orci ullamcorper urna, nec rutrum lacus elit a metus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin eu nulla lectus, id porttitor quam. Curabitur a quam vitae dui sagittis pretium. Fusce in urna est.</p>
		</div>
	</div>
<div>
</body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/feedback">feedback page</a>.
</p>

app/views/pages/home.html.erb
<h1>Sample App</h1>
<p>
  This is the home page for the
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</p>

app/views/pages/services.html.erb
	<div class="row">
		<div class="span9"><h1>Services</h1>
<p>
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p></div>

	</div>

app/views/portfolios/_form.html.erb
<%= simple_form_for @portfolio, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                portfolios_path, :class => 'btn' %>
  </div>
<% end %>

app/views/portfolios/edit.html.erb
<%- model_class = @portfolio.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/portfolios/index.html.erb
<%- model_class = Portfolio.new.class -%>
<h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @portfolios.each do |portfolio| %>
      <tr>
        <td><%= link_to portfolio.id, portfolio_path(portfolio) %></td>
        <td><%= portfolio.name %></td>
        <td><%= portfolio.description %></td>
        <td><%=l portfolio.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_portfolio_path(portfolio), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      portfolio_path(portfolio),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_portfolio_path,
            :class => 'btn btn-primary' %>

app/views/portfolios/new.html.erb
<%- model_class = @portfolio.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/portfolios/show.html.erb
<%- model_class = @portfolio.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<p>
  <strong><%= model_class.human_attribute_name(:name) %>:</strong><br>
  <%= @portfolio.name %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:description) %>:</strong><br>
  <%= @portfolio.description %>
</p>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              portfolios_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_portfolio_path(@portfolio), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              portfolio_path(@portfolio),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>